version: '3.8'

services:
  app:
    build: .
    container_name: todo-app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - .env
    networks:
      - todo-network

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network

volumes:
  mongo-data:
    driver: local

networks:
  todo-network:
    driver: bridge
